name: BetterQuests
version: "1.0.0"
main: dev.itzstevee.quests.QuestsPlugin
description: "High-performance quest system with MongoDB and PlaceholderAPI."
author: ItzStevee
api-version: "1.21"
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
commands:
  quests:
    description: "Open the quest journal"
    usage: "/<command>"
  questadmin:
    description: "Quest admin commands"
    usage: "/<command> <setprogress|reset|reload>"
    permission: quests.admin
permissions:
  quests.admin:
    description: "Allows access to quest admin commands"
    default: op

